# Generated by Django 4.2.2 on 2023-06-28 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_city', models.CharField(max_length=50)),
                ('location_state', models.CharField(max_length=50)),
                ('location_state_abbr', models.CharField(max_length=3)),
                ('stadium_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('team_location', models.CharField(max_length=50)),
                ('team_color_1', models.CharField(max_length=7)),
                ('team_color_2', models.CharField(max_length=7)),
                ('team_logo', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField()),
                ('schedule_time', models.TimeField()),
                ('schedule_week', models.IntegerField()),
                ('schedule_season', models.IntegerField()),
                ('schedule_away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='pick_em.team')),
                ('schedule_home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='pick_em.team')),
                ('schedule_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pick_em.location')),
            ],
        ),
    ]
