# Generated by Django 4.2.2 on 2023-06-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pick_em', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
