# Generated by Django 4.2.2 on 2023-07-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pick_em', '0004_league_picks_league_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picks',
            name='game_id',
        ),
        migrations.RemoveField(
            model_name='picks',
            name='pick_team_id',
        ),
        migrations.AddField(
            model_name='picks',
            name='picks',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='picks',
            name='week',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
