# Generated by Django 4.2.2 on 2023-07-27 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pick_em', '0005_remove_picks_game_id_remove_picks_pick_team_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picks',
            name='picks',
        ),
        migrations.RemoveField(
            model_name='picks',
            name='week',
        ),
        migrations.AddField(
            model_name='picks',
            name='game_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pick_em.schedule'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picks',
            name='outcome',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='picks',
            name='pick_team_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pick_em.team'),
        ),
        migrations.AddField(
            model_name='picks',
            name='point_stake',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='picks',
            name='points_awarded',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
