# Generated by Django 4.2.2 on 2023-09-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pick_em', '0006_remove_picks_picks_remove_picks_week_picks_game_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picks',
            name='point_stake',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
