# Generated by Django 4.2.2 on 2023-09-08 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pick_em', '0007_alter_picks_point_stake'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='away_team_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='game_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='game_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_winner', to='pick_em.team'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='home_team_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
